- name: Create directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  with_items: "{{ filecreate_directories }}"

- name: Create files with content
  copy:
    dest: "{{ item.filepath }}"
    content: "{{ item.content }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ filecreate_files }}"
  no_log: "{{ filecreate_no_log | bool }}"
